#CI de Nível 3 - Disparo automático sempre que outro for concluído, como deploy

name: 'Execução por Deploy'

#regras de disparo da execução (triggers)
#no github actions, gatilho de exec.após outro workflow = workflow_run
on:
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed

jobs:
  #descricao do job
  e2e-tests:
    #maquina que o job vai executar
    runs-on: ['ubuntu-latest']

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    #passo a passo da acoes do job
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
