#CI de Nível 4 - Disparo dentro do fluxo de CI de desenvolvimento

#nome que vai aparecer na opções de pipe
name: 'Execução Integrada'

#regras de disparo da execução (triggers)
#no github actions, gatilho de exec.manual = workflow_dispatch
on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Padronização de código (Lint)
        run: yarn lint

  unit:
    runs-on: ['ubuntu-latest']
    needs: [inspection]

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Testes de unidade
        run: yarn run test

  #descricao do job
  e2e-tests:
    #maquina que o job vai executar
    runs-on: ['ubuntu-latest']
    needs: [unit]

    #passo a passo da acoes do job
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Subir aplicação local
        run: yarn start &

      - name: Testes E2E (end-to-end)
        run: yarn run e2e
        env:
          URL: 'http://localhost:3000'

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report

  deploy:
    #maquina que o job vai executar
    runs-on: ['ubuntu-latest']
    needs: [e2e-tests]
    steps:
      - name: Deploy
        run: echo "step deploy"
